---
title: "Analysis"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

# Libraries and imports
```{r}
library(tidyverse)
library(foreign)
library(NbClust)
library(fpc)
library(GGally)
library(ggrepel)
library(ggfortify)
library(rcompanion)
set.seed(44)

NBA.df <- read_csv('Data/season_stats_clean.csv')
names(NBA.df)[3] <- "Team"

```


# Data cleanup
Why did we decide on these columns?

```{r}
# set the columns to keep
cols.to.keep <- c("Player", "Pos", "Age", "Team", "Salary", "RPM", grep('_pg', names(NBA.df), value = TRUE))
NBA.df <- NBA.df[, cols.to.keep]
```

# EDA

```{r EDA}
# set the columns to explore
cols.to.explore <- grep('_pg', names(NBA.df), value = TRUE)

# range of the data
diff(apply(NBA.df[, cols.to.explore], MARGIN = 2, FUN = range))

# biavariate plot
# ggpairs(data = NBA.df, columns = cols.to.explore)

# bivariate plot of log values
# NBA.df %>% 
#   select(cols.to.explore) %>% 
#   mutate_all(log) %>% 
#   ggpairs()
```

## Standardize and take the log of the data

```{r}
# use Tukey Ladder of Powers to normalize the data
NBA.stdz <- lapply(NBA.df[, cols.to.explore], transformTukey, plotit = FALSE, quiet = TRUE) %>% 
  as_tibble()

# scale the data
NBA.stdz <- scale(NBA.stdz) %>% as_tibble()

# add back in the orginal attributes
NBA.stdz <- bind_cols(NBA.df[, c("Player", "Pos", "Age", "Team", "Salary", "RPM")], NBA.stdz)

```


Log transform may not be neccessary
```{r DELETE}
# NBA.stdz <- NBA.df
# 
# # add some noise to remove 0s which will avoid -Inf after log transformation
# NBA.stdz[, cols.to.keep] <- apply(NBA.stdz[, cols.to.keep], MARGIN = 2, jitter, amount = 0.001)
# 
# # apply log and scale
# NBA.stdz[, cols.to.keep] <- log(NBA.stdz[, cols.to.keep])
# NBA.stdz[, cols.to.keep] <- scale(NBA.stdz[, cols.to.keep])
# 
# # remove NaNs from the cols.to.keep columns only then join back to original
# # data using a new index column
# NBA.stdz <- NBA.stdz %>% 
#   mutate(Index = row_number()) %>% 
#   select(c(cols.to.keep, "Index")) %>% 
#   na.omit() %>% 
#   left_join(y = mutate(NBA.stdz[, c("Player", "Pos", "Age", "Team")],
#                        Index = row_number()),
#             by = "Index") %>% 
#   select(-Index)
# 
# ggpairs(data = NBA.stdz, columns = cols.to.keep)
```

## Principle Component Analysis
```{r PCA}
# principle component analysis
NBA.pca <- princomp(NBA.stdz[, cols.to.explore])

# examine the pc
summary(NBA.pca)
NBA.pca$loadings

# plot the clusters in PCA space
autoplot(NBA.pca, data = NBA.df, colour = 'Pos') + 
  geom_label_repel(aes(label = ifelse(MP_pg >= 36 | MP_pg <= 3, 
                                      as.character(sub("^\\S+\\s+", '', Player)), '' )),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey80') +
  theme_minimal()

```


# Clustering
```{r}
# NbClust(data = NBA.stdz[, cols.to.keep], method = 'centroid', index = 'ch')

# is nbClust to find optimal k value under C(g)
km.clusts <- NbClust(data = NBA.stdz[, cols.to.explore], method = 'kmeans', index = 'ch')
plot(x = NBA.pca$scores[,'Comp.1'],
     y = NBA.pca$scores[,'Comp.2'],
     col = km.clusts$Best.partition)

plot(x = names(km.clusts$All.index),
     y = km.clusts$All.index,
     xlab = "k",
     ylab = "C(g)",
     type = "l")

# re cluster using kmeans()
km.clusts <- kmeans(x = NBA.stdz[, cols.to.explore], centers = 4, nstart = 100)


# plot of clustering in PC space
NBA.stdz %>% 
  cbind(cluster = km.clusts$cluster,
        NBA.pca$scores[, 1:2]) %>% 
  mutate(Cluster = as.factor(cluster),
         Player = sub("^\\S+\\s+", '', Player)) %>% 
  ggplot(aes(x = Comp.1, y = Comp.2)) +
  geom_text(aes(label = Player,
                col = Cluster,
                size = Salary,
                alpha = RPM),
            hjust = 0,
            vjust = 0)

```

# Post-hoc anlayses

```{r}
# scatterplot of RPM vs. Salary
ggplot(NBA.df, aes(x = RPM, y = Salary,
                   color = as.factor(km.clusts$cluster),
                   text = paste("Player:", Player))) +
  geom_point() +
  scale_y_continuous(labels = scales::dollar) +
  labs(col = "Cluster membership") +
  theme_minimal()

# interactive plot
plotly::ggplotly()

```


